### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by silvestreh** [olivierperez/o80-i18n#3]
Does this library automatically add keys for the missing translations to the JSON dictionary?

**Comment by olivierperez** [comment]
Hi, o80-i18n just read dictionary. It doesn't modify it.
If you ask for a missing key, it will return `[missing key:SECTION.KEY]`.

However, if you need the library to fix your dictionnary, I propose you to improve o80-i18n by adding a new class that compares (and fix) 2 dictionnary. It could eventually add missing keys and/or reorder a dictionnary.

Stay tuned.
