### ISSUE TITLE
howto: regenerate locale from source code?

### ISSUE THREAD

**Issue by bagage** [olivierperez/o80-i18n#6]
Is there any way to do it or should it be done manually? 
I am currently using some shell script eg `ag '__\(' | sed 's/.*__\((.*)\).*/\1/g' | cut -d ')' -f 1 | sort | uniq` + extra processing but is there anything better here? 
And are there any rules for sorting sections in `locale` file?

Thanks,

**Comment by olivierperez** [comment]
Hi,

There is still no script nor code to generate locale from source code.
It would be nice if you can propose a Pull Request if you want to contribute to this library.
